spring.application.name=Banca
server.port=8081

spring.datasource.url = jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
spring.datasource.username = banca
spring.datasource.password = banca

spring.jpa.show-sql= true
spring.jpa.hibernate.ddl-auto = none
spring.datasource.driver-class-name= oracle.jdbc.OracleDriver


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=trace
logging.level.org.hibernate.engine.internal=DEBUG

